version: '3.8'
services:
  web:
    build:
      context: .
    ports:
      - 8080:4567
      - 35729:35729
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    command: bundle exec middleman server
