version: '3.8'
services:
  web:
    image: emmajhyde/emmahy_de:latest
    ports:
      - 443:4567
    environment:
      NODE_ENV: production
    command: >
      bash -c "cd /app
      && bundle exec middleman server --port=8080 --environment=production --relative-links=true --watcher-disable --bind-address=0.0.0.0"
